<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AkgBalitaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('akg_balitas')->truncate();

        DB::table('akg_balitas')->insert([

            // ================== 0 - 5 BULAN ==================
            [
                'umur_awal' => 0,
                'umur_akhir' => 5,
                'label_kelompok' => '0 - 5 bulan',
                'energi_kkal' => 550,
                'protein_g' => 9,
                'lemak_g' => 31,
                'karbohidrat_g' => 59,
                'serat_g' => 0,
                'air_ml' => 700,

                // ---- Vitamin (Tabel 2) ----
                'vit_a_re' => 375,
                'vit_d_mcg' => 10,
                'vit_e_mcg' => 4,
                'vit_k_mcg' => 5,
                'vit_b1_mg' => 0.2,
                'vit_b2_mg' => 0.3,
                'vit_b3_mg' => 2,
                'vit_b5_mg' => 1.7,
                'vit_b6_mg' => 0.1,
                'folat_mcg' => 80,
                'vit_b12_mcg' => 0.4,
                'biotin_mcg' => 5,
                'kolin_mg' => 125,
                'vit_c_mg' => 40,

                // ---- Mineral (Tabel 3) ----
                'kalsium_mg' => 200,
                'fosfor_mg' => 100,
                'magnesium_mg' => 30,
                'besi_mg' => 0.3,
                'iodium_mcg' => 90,
                'seng_mg' => 1.1,
                'selenium_mcg' => 7,
                'mangan_mg' => 0.003,
                'fluor_mg' => 0.01,
                'kromium_mcg' => 0.2,
                'kalium_mg' => 400,
                'natrium_mg' => 120,
                'klor_mg' => 180,
                'tembaga_mcg' => 200,

                'padanan' => json_encode([
                    'Energi'      => 'ASI diberikan sesering keinginan bayi, minimal 8-12 kali sehari termasuk malam hari',
                    'Protein'     => 'seluruhnya tercukupi dari ASI',
                    'Lemak'       => 'seluruhnya tercukupi dari ASI; lemak ASI penting untuk pertumbuhan otak bayi',
                    'Karbohidrat' => 'seluruhnya tercukupi dari ASI (laktosa)',
                    'Serat'       => 'belum dibutuhkan; bayi usia ini belum boleh diberi makanan padat',
                    'Air'         => 'seluruhnya dari ASI; tidak perlu air putih atau cairan tambahan lain',
                    'Vitamin & Mineral' => 'seluruh vitamin dan mineral tercukupi dari ASI ibu yang bergizi baik; vitamin K diberikan lewat suntikan saat lahir, dan jemur bayi di matahari pagi membantu vitamin D',
                ]),
                'catatan' => 'Seluruh kebutuhan gizi pada usia ini dipenuhi dari pemberian ASI eksklusif. Belum diperkenankan makanan atau minuman lain.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ================== 6 - 11 BULAN ==================
            [
                'umur_awal' => 6,
                'umur_akhir' => 11,
                'label_kelompok' => '6 - 11 bulan',
                'energi_kkal' => 800,
                'protein_g' => 15,
                'lemak_g' => 35,
                'karbohidrat_g' => 105,
                'serat_g' => 11,
                'air_ml' => 900,

                'vit_a_re' => 400,
                'vit_d_mcg' => 10,
                'vit_e_mcg' => 5,
                'vit_k_mcg' => 10,
                'vit_b1_mg' => 0.3,
                'vit_b2_mg' => 0.4,
                'vit_b3_mg' => 4,
                'vit_b5_mg' => 1.8,
                'vit_b6_mg' => 0.3,
                'folat_mcg' => 80,
                'vit_b12_mcg' => 1.5,
                'biotin_mcg' => 6,
                'kolin_mg' => 150,
                'vit_c_mg' => 50,

                'kalsium_mg' => 270,
                'fosfor_mg' => 275,
                'magnesium_mg' => 55,
                'besi_mg' => 11,
                'iodium_mcg' => 120,
                'seng_mg' => 3,
                'selenium_mcg' => 10,
                'mangan_mg' => 0.7,
                'fluor_mg' => 0.5,
                'kromium_mcg' => 6,
                'kalium_mg' => 700,
                'natrium_mg' => 370,
                'klor_mg' => 570,
                'tembaga_mcg' => 220,

                'padanan' => json_encode([
                    'Energi'      => 'ASI tetap diberikan + MPASI 2-3 kali sehari dan 1-2 kali makanan selingan',
                    'Protein'     => 'kira-kira 1 butir telur + 1 potong kecil ikan/ayam/hati yang dilumatkan, ditambah ASI',
                    'Lemak'       => 'sebagian besar dari ASI; tambahkan sekitar 1 sdt minyak/santan ke dalam MPASI setiap kali memasak',
                    'Karbohidrat' => 'bubur atau nasi tim sekitar 1/2 - 3/4 mangkuk kecil (250 ml) setiap kali makan',
                    'Serat'       => 'sayur lembut 2-3 sdm tiap kali makan + buah lumat (pisang/pepaya) 1-2 kali sehari',
                    'Air'         => 'sebagian besar dari ASI; air putih cukup sekitar 1/2 gelas kecil sehari',
                    'Vitamin A'   => 'kapsul biru dari posyandu (Februari/Agustus) + hati ayam, wortel, atau labu kuning yang dilumatkan',
                    'Zat Besi'    => 'paling tinggi kebutuhannya di usia ini: hati ayam, daging merah, atau kuning telur lumat hampir setiap hari',
                    'Seng'        => 'daging, ayam, ikan, dan telur dalam MPASI; penting untuk mencegah stunting',
                    'Kalsium & Vitamin D' => 'ASI, ikan lumat, dan berjemur matahari pagi 10-15 menit',
                    'Vitamin C'   => 'buah lumat seperti jeruk manis, pepaya, atau jambu 1-2 kali sehari',
                    'Iodium'      => 'gunakan garam beriodium secukupnya dalam MPASI + ikan laut lumat',
                    'Folat'       => 'sayur hijau lumat (bayam, brokoli) dan kacang-kacangan halus',
                ]),
                'catatan' => 'ASI tetap diberikan, didampingi MPASI bergizi seimbang (karbohidrat, protein hewani, protein nabati, sayur dan buah) sesuai tekstur usianya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ================== 1 - 3 TAHUN ==================
            [
                'umur_awal' => 12,
                'umur_akhir' => 47,
                'label_kelompok' => '1 - 3 tahun',
                'energi_kkal' => 1350,
                'protein_g' => 20,
                'lemak_g' => 45,
                'karbohidrat_g' => 215,
                'serat_g' => 19,
                'air_ml' => 1150,

                'vit_a_re' => 400,
                'vit_d_mcg' => 15,
                'vit_e_mcg' => 6,
                'vit_k_mcg' => 15,
                'vit_b1_mg' => 0.5,
                'vit_b2_mg' => 0.5,
                'vit_b3_mg' => 6,
                'vit_b5_mg' => 2.0,
                'vit_b6_mg' => 0.5,
                'folat_mcg' => 160,
                'vit_b12_mcg' => 1.5,
                'biotin_mcg' => 8,
                'kolin_mg' => 200,
                'vit_c_mg' => 40,

                'kalsium_mg' => 650,
                'fosfor_mg' => 460,
                'magnesium_mg' => 65,
                'besi_mg' => 7,
                'iodium_mcg' => 90,
                'seng_mg' => 3,
                'selenium_mcg' => 18,
                'mangan_mg' => 1.2,
                'fluor_mg' => 0.7,
                'kromium_mcg' => 14,
                'kalium_mg' => 2600,
                'natrium_mg' => 800,
                'klor_mg' => 1200,
                'tembaga_mcg' => 340,

                'padanan' => json_encode([
                    'Energi'      => '3 kali makan utama + 2 kali selingan sehat (buah, bubur kacang hijau)',
                    'Protein'     => 'kira-kira 1 butir telur + 1 potong kecil ikan/ayam + 1 potong tempe/tahu sehari',
                    'Lemak'       => 'sekitar 2-3 sdt minyak untuk memasak + lemak alami dari lauk dan santan secukupnya',
                    'Karbohidrat' => 'nasi sekitar 3 porsi kecil sehari (1 porsi = 3/4 gelas), boleh berganti ubi/kentang/roti',
                    'Serat'       => 'sayur sekitar 1,5 gelas + buah 2-3 potong kecil sehari',
                    'Air'         => 'sekitar 5 gelas kecil (200 ml) sehari',
                    'Vitamin A'   => 'kapsul merah dari posyandu (Februari/Agustus) + telur, hati, wortel, atau sayuran hijau',
                    'Zat Besi'    => 'daging merah/hati/ikan 1 potong kecil hampir tiap hari + sayur hijau; bantu penyerapan dengan buah ber-vitamin C',
                    'Seng'        => 'lauk hewani (daging, ayam, ikan, telur) setiap hari',
                    'Kalsium & Vitamin D' => '1 gelas susu atau padanannya (ikan teri, tempe, tahu) + bermain di matahari pagi',
                    'Vitamin C'   => '1-2 buah segar sehari: jeruk, pepaya, jambu biji, atau mangga',
                    'Iodium'      => 'selalu pakai garam beriodium di masakan keluarga + ikan laut 2-3 kali seminggu',
                    'Folat'       => 'sayur hijau (bayam, kangkung, brokoli) dan kacang-kacangan setiap hari',
                ]),
                'catatan' => 'Anak mulai mengonsumsi makanan keluarga. Utamakan keberagaman: makanan pokok, lauk hewani, lauk nabati, sayur, dan buah setiap hari.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ================== 4 - 6 TAHUN ==================
            [
                'umur_awal' => 48,
                'umur_akhir' => 72,
                'label_kelompok' => '4 - 6 tahun',
                'energi_kkal' => 1400,
                'protein_g' => 25,
                'lemak_g' => 50,
                'karbohidrat_g' => 220,
                'serat_g' => 20,
                'air_ml' => 1450,

                'vit_a_re' => 450,
                'vit_d_mcg' => 15,
                'vit_e_mcg' => 7,
                'vit_k_mcg' => 20,
                'vit_b1_mg' => 0.6,
                'vit_b2_mg' => 0.6,
                'vit_b3_mg' => 8,
                'vit_b5_mg' => 3.0,
                'vit_b6_mg' => 0.6,
                'folat_mcg' => 200,
                'vit_b12_mcg' => 1.5,
                'biotin_mcg' => 12,
                'kolin_mg' => 250,
                'vit_c_mg' => 45,

                'kalsium_mg' => 1000,
                'fosfor_mg' => 500,
                'magnesium_mg' => 95,
                'besi_mg' => 10,
                'iodium_mcg' => 120,
                'seng_mg' => 5,
                'selenium_mcg' => 21,
                'mangan_mg' => 1.5,
                'fluor_mg' => 1.0,
                'kromium_mcg' => 16,
                'kalium_mg' => 2700,
                'natrium_mg' => 900,
                'klor_mg' => 1300,
                'tembaga_mcg' => 440,

                'padanan' => json_encode([
                    'Energi'      => '3 kali makan utama + 2 kali selingan sehat',
                    'Protein'     => 'kira-kira 1 butir telur + 1 potong ikan/ayam + 2 potong tempe/tahu, atau ditambah 1 gelas susu',
                    'Lemak'       => 'sekitar 3 sdt minyak untuk memasak + lemak alami dari lauk',
                    'Karbohidrat' => 'nasi 3-4 porsi sehari (1 porsi = 3/4 gelas), boleh berganti ubi/kentang/mi/roti',
                    'Serat'       => 'sayur sekitar 2 gelas + buah 3 potong sehari',
                    'Air'         => 'sekitar 6 gelas (240 ml) sehari',
                    'Vitamin A'   => 'telur, hati, ikan, wortel, dan sayuran hijau dalam menu harian',
                    'Zat Besi'    => 'daging merah/hati/ikan 1 potong hampir tiap hari + sayur hijau; sertakan buah ber-vitamin C agar terserap baik',
                    'Seng'        => 'lauk hewani setiap hari (daging, ayam, ikan, telur)',
                    'Kalsium & Vitamin D' => 'kebutuhan kalsium naik di usia ini: 1-2 gelas susu + ikan teri/tempe/tahu + aktivitas luar ruang pagi hari',
                    'Vitamin C'   => '2 porsi buah segar sehari: jeruk, jambu biji, pepaya, atau mangga',
                    'Iodium'      => 'garam beriodium di masakan + ikan laut 2-3 kali seminggu',
                    'Folat'       => 'sayur hijau dan kacang-kacangan setiap hari',
                ]),
                'catatan' => 'Pertahankan pola makan gizi seimbang dan batasi gula, garam, serta makanan ringan kemasan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
